### ISSUE TITLE
Question: Having trouble installing apexpy on my Win10

### ISSUE THREAD

**Issue by bonnietedder** [aburrell/apexpy#125]
Tried many ways to install apexpy but failed anyway
========================================
I followed all the instructions trying to get apexpy installed but so far none of the methods worked.

In general, using pip to install apexpy, errors always show up as:
---------------------------------
Collecting apexpy
  Using cached apexpy-2.0.1.tar.gz (328 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      + meson setup C:\Users\lenovo\AppData\Local\Temp\pip-install-09lazxqs\apexpy_83ad6f6bffa44decb5e6df37494f7225 C:\Users\lenovo\AppData\Local\Temp\pip-install-09lazxqs\apexpy_83ad6f6bffa44decb5e6df37494f7225\.mesonpy-xuc4bmle\build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=C:\Users\lenovo\AppData\Local\Temp\pip-install-09lazxqs\apexpy_83ad6f6bffa44decb5e6df37494f7225\.mesonpy-xuc4bmle\build\meson-python-native-file.ini
      The Meson build system
      Version: 1.1.1
      Source dir: C:\Users\lenovo\AppData\Local\Temp\pip-install-09lazxqs\apexpy_83ad6f6bffa44decb5e6df37494f7225
      Build dir: C:\Users\lenovo\AppData\Local\Temp\pip-install-09lazxqs\apexpy_83ad6f6bffa44decb5e6df37494f7225\.mesonpy-xuc4bmle\build
      Build type: native build
      Project name: apexpy
      Project version: 2.0.1
      WARNING: Failed to activate VS environment: Could not find C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe

      ..\..\meson.build:1:0: ERROR: Unknown compiler(s): [['icl'], ['cl'], ['cc'], ['gcc'], ['clang'], ['clang-cl'], ['pgcc']]

Furthermore, I found out the error message could be related to installing mensopy, I put error messages below when applying pip install mensopy
---------------------------------
Collecting mesonpy
  Using cached MesonPy-0.0.1.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\lenovo\AppData\Local\Temp\pip-install-qx7wr5pp\mesonpy_ee9de1d9b0344322ba84ab990f40e9c3\setup.py", line 4, in <module>
          with open('requirements.txt') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Expectations
------------
Want to find a way getting apexpy installed.

Screenshots
-----------
![image](https://github.com/aburrell/apexpy/assets/37703525/c2582d13-ee37-49be-b4bb-566c46d0106d)

Computer
--------
* OS: win10
* Python version: 3.9.6
* Compiler with version: no idea
* Apexpy version/branch: no idea

Additional context
------------------
Thank you so much for making this apexpy package.

**Comment by aburrell** [comment]
Hi @bonnietedder, sorry for the long delay.  Windows is not my strong suit, but it looks like you probably don't have a fortran compiler installed (the error message is listing out a bunch of common compilers and it looks like you don't have any of them).  Can you check that you have installed:

1) Windows developer tools
2) gcc
3) gfortran

For our continuous integration testing we use the following commands (which should only be tried *after* making sure you have the windows developer tools.  If you don't do that first you have to re-install everything all over again):
```
choco install ninja mingw
choco install rtools --no-progress
```
Mingw should get you gcc and gfortran.  You can test this by:

```
gfortran --version
```

If that works, you're good to try the apexpy install.
